# Generated by Django 3.0.7 on 2020-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20201001_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20),
        ),
    ]
