# Generated by Django 3.0.7 on 2020-10-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20191212_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='approved_contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_paymentVerification',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_price',
            field=models.IntegerField(blank=True),
        ),
    ]
