# Generated by Django 3.0.7 on 2020-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_contract_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='semester',
        ),
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.CharField(choices=[('1', 'CONTRACT'), ('2', 'SALES'), ('3', 'HELPING HANDS'), ('4', 'OUTDOORS')], default='1', max_length=20),
        ),
    ]
