# Generated by Django 3.0.7 on 2020-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20201003_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
